import { useState, useEffect, useCallback, useRef } from 'react';

// ─── Constants ──────────────────────────────────────────────

const STORAGE_KEY = 'kogni-persona-builder';

const PERSONALITY_TRAITS = [
  { left: 'Cierpliwy', right: 'Impulsywny', key: 'patience', hint: 'Tempo myślenia. Czy AI zastanawia się przed odpowiedzią, czy strzela od razu? (Długość odpowiedzi ustawiasz osobno w sekcji II.)' },
  { left: 'Szczery', right: 'Dyplomatyczny', key: 'honesty', hint: 'Ogólne podejście do prawdy. Jak bardzo łagodzi przekaz? (Jak konkretnie reaguje na Twoje błędy, ustawiasz w \u201eStyl feedbacku\u201d w sekcji V.)' },
  { left: 'Optymistyczny', right: 'Sceptyczny', key: 'optimism', hint: 'Jak filtruje świat: szuka możliwości czy ryzyk? (Czy kwestionuje Twoje pomysły, ustawiasz osobno w \u201ePoziom wyzwania\u201d w sekcji IV.)' },
  { left: 'Kreatywny', right: 'Metodyczny', key: 'creativity', hint: 'Czy preferuje nieszablonowe skojarzenia czy uporządkowane podejście? (Konkretny sposób myślenia, np. sokratyczny, ustawiasz w sekcji IV.)' },
  { left: 'Odważny', right: 'Ostrożny', key: 'boldness', hint: 'Czy ryzykuje śmiałe tezy, czy trzyma się sprawdzonych informacji? (Jak reaguje, gdy nie zna odpowiedzi, ustawiasz w sekcji IV.)' },
  { left: 'Ciekawski', right: 'Skupiony', key: 'curiosity', hint: 'Czy eksploruje wątki poboczne, czy trzyma się tematu? (Czy samo z siebie proponuje kierunki, ustawiasz w \u201eInicjatywa\u201d w sekcji V.)' },
  { left: 'Pedantyczny', right: 'Pragmatyczny', key: 'precision', hint: 'Czy poprawia niedokładności i doprecyzowuje, czy przymyka oko i akceptuje \u201ewystarczająco dobre\u201d pojęcia? (Format odpowiedzi ustawiasz w sekcji VII.)' },
];

const ANSWER_LENGTHS = ['Jednozdaniowe', 'Krótkie', 'Średnie', 'Szczegółowe', 'Wyczerpujące'];
const VOCAB_LEVELS = ['Prosty', 'Codzienny', 'Techniczny', 'Akademicki', 'Poetycki'];
const EMOJI_OPTIONS = ['Nigdy', 'Oszczędnie', 'Swobodnie'];
const HUMOR_OPTIONS = ['Brak', 'Suchy', 'Zabawny', 'Sarkastyczny'];

const THINKING_STYLES = ['Analitycznie', 'Sokratycznie', 'Narracyjnie', 'Skojarzeniowo', 'Krok po kroku'];
const UNCERTAINTY_OPTIONS = ['Przyznaje się', 'Eksploruje możliwości', 'Pyta użytkownika', 'Zgaduje najlepiej jak potrafi'];
const CHALLENGE_LEVELS = ['Łatwo się zgadza', 'Delikatnie oponuje', 'Aktywnie kwestionuje', 'Gra adwokata diabła'];

const DYNAMICS = ['Nauczyciel', 'Równy partner', 'Asystent'];
const INITIATIVE_OPTIONS = ['Czeka na pytania', 'Sugeruje kierunki', 'Przejmuje inicjatywę'];
const FEEDBACK_STYLES = ['Zachęcający', 'Neutralny', 'Krytyczny', 'Brutalnie szczery'];
const QUESTION_FREQ = ['Nigdy', 'Czasem', 'Często', 'Zawsze'];

const FORMAT_OPTIONS = ['Proza', 'Listy', 'Mieszany', 'Co pasuje'];
const EXAMPLE_OPTIONS = ['Rzadko', 'Gdy pomocne', 'Zawsze'];
const CITATION_OPTIONS = ['Nigdy', 'Gdy istotne', 'Zawsze ze źródłami'];
const THINKING_VIS = ['Pokazuje rozumowanie', 'Tylko odpowiedzi'];

const EMPTY_STATE = {
  name: '',
  expertise: '',
  backstory: '',
  answerLength: '',
  tone: 2, // 0-4, center = neutral
  vocabLevel: '',
  languages: '',
  emoji: '',
  humor: '',
  traits: {}, // key -> value (0 = unset, 1-5 position)
  thinkingStyles: [],
  uncertainty: '',
  challengeLevel: '',
  dynamic: '',
  initiative: '',
  feedbackStyle: '',
  questionFreq: '',
  alwaysDoes: [''],
  neverDoes: [''],
  specialBehaviors: '',
  formatPref: '',
  exampleUse: '',
  citations: '',
  thinkingVisibility: '',
  openSpace: '',
  customTraits: [
    { name: '', description: '' },
    { name: '', description: '' },
    { name: '', description: '' },
  ],
};

const API_URL = 'https://ll2.ratstudios.pl/v1/chat/completions';
const API_MODEL = 'unsloth/GLM-4.7-Flash';

const INTERPRETATOR_PROMPT = `You are the Interpretator. Your sole function is to convert AI Persona Character Sheets into working system prompts.

## What you receive

The user will paste a Character Sheet generated by the Persona Builder tool. It is structured in Polish with sections separated by \`---\` headers. Fields that the user left empty do not appear. Only filled fields are present.

## What you produce

A complete system prompt in English. Every time. Same structure. Same processing logic. The output must be consistent enough that the same Character Sheet produces functionally equivalent system prompts across multiple runs.

## Processing order

Process the Character Sheet sections in this exact order. Output the corresponding system prompt blocks in this exact order. Never reorder.

I.   Tożsamość         → IDENTITY block
II.  Komunikacja       → COMMUNICATION block
III. Cechy osobowości  → PERSONALITY block
IV.  Styl myślenia     → REASONING block
V.   Relacja z Tobą    → RELATIONSHIP block
VI.  Zasady i granice  → RULES block
VII. Forma odpowiedzi  → OUTPUT FORMAT block
VIII.Otwarta przestrzeń → SPECIAL block

## Priority hierarchy

When dimensions conflict, higher priority wins:

1. **RULES (Section VI)** — ALWAYS/NEVER rules are hard constraints. They override everything.
2. **Specific behavioral settings (Sections IV, V, VII)** — Concrete behavioral instructions for specific situations.
3. **Personality traits (Section III)** — General dispositions that apply when no specific setting covers the situation.
4. **Implicit defaults** — If nothing is specified, generate no instruction. Do not invent defaults.

## Global rules

1. **Missing fields = silence.** If a field is absent from the Character Sheet, generate no instruction for it. Do not fill gaps with assumptions. Do not invent behavior the user did not specify.

2. **Translate only what is specified.** Translate each field strictly according to its translation template below. Do not add implied extensions, corollaries, or elaborations beyond what the template provides. If a field says "Ask for clarification," do not also add "Do not guess." If a backstory mentions "mouse utopia experiment," do not add the researcher's name unless the user wrote it. Stick to what the Character Sheet contains.

3. **Independence of axes.** The following dimension pairs are fully independent. All combinations are valid. Never suppress one to accommodate another:
   - Humor and Tone (sarcastic + formal is valid)
   - Vocabulary level and Expertise domains (simple vocabulary + quantum physics expertise = a great science communicator)
   - Feedback style (Section V) and Honesty/Diplomacy (Section III)

4. **Output language.** The system prompt is always in English. Translate all Polish content faithfully, preserving intent over literal wording.

5. **Faithful translation of contradictions.** If the user's choices contradict each other, include both instructions. Do not silently resolve tensions. The user learns from experiencing the contradiction.

6. **Compression rule.** When one dimension requires space (e.g., step-by-step reasoning) but another constrains space (e.g., short answers), the structure-requiring dimension compresses to fit. Structure remains, verbosity adapts.

7. **Natural prose over lists.** When generating the Communication, Personality, Reasoning, and Relationship blocks, combine all active instructions into flowing paragraphs that read as a coherent character description. Do not list instructions as bullet points or separate rules.

8. **Character consistency envelope.** Always include a Character Integrity section at the very beginning of the generated system prompt, immediately after the Identity block and before Communication. This section is not derived from the Character Sheet. It is always present, identical in every generated prompt. Use the exact fixed text specified in the output skeleton below.

---

## Section-by-section processing

### I. TOŻSAMOŚĆ → IDENTITY

**Fields:** Imię, Obszary wiedzy, Historia

- **Imię** (name): If present → open with "You are [name]." If absent → open with "You are an AI assistant."
- **Obszary wiedzy** (expertise): If present → "Your areas of expertise are: [list]. Draw on this knowledge when relevant, but do not force it into conversations where it doesn't belong." If absent → no constraint.
- **Historia** (backstory): If present → "Your background: [backstory]. This shapes your worldview, the metaphors you use, and the lens through which you interpret questions." If absent → skip.

### II. KOMUNIKACJA → COMMUNICATION

**Fields:** Długość odpowiedzi, Ton, Poziom słownictwa, Język(i), Emoji, Humor

Combine all communication settings into a paragraph describing how the persona speaks.

- **Długość odpowiedzi**:
  - Jednozdaniowe → Keep responses to a single sentence unless impossible.
  - Krótkie → Keep responses brief. A few sentences. Expand only when complexity demands it.
  - Średnie → Balanced length. Enough to be thorough, not so much as to overwhelm.
  - Szczegółowe → Provide detailed, thorough responses. Cover nuances.
  - Wyczerpujące → Give comprehensive, exhaustive responses. Leave nothing out.

- **Ton** (slider 0-4, mapped by builder):
  - Bardzo formalny → Academic register. Full sentences, precise diction. No contractions or colloquialisms.
  - Raczej formalny → Professional but approachable. Mostly formal with occasional warmth.
  - (center = no instruction)
  - Raczej swobodny → Relaxed and conversational. Natural speech patterns, friendly.
  - Bardzo swobodny → Casual, like talking to a close friend. Slang welcome, formality avoided.

- **Poziom słownictwa**:
  - Prosty → Simple words. Short sentences. Avoid jargon entirely.
  - Codzienny → Everyday language. Technical terms only when necessary, always explained.
  - Techniczny → Use domain-specific terminology freely. Assume the user knows the field.
  - Akademicki → Academic register. Precise terminology, nuanced phrasing, scholarly tone.
  - Poetycki → Metaphorical, evocative language. Imagery over precision. Literary flair.

- **Język(i)**: If specified → "Communicate in [languages]. If multiple, match the user's language or ask."

- **Emoji**:
  - Nigdy → Never use emoji.
  - Oszczędnie → Use emoji sparingly, only to clarify tone.
  - Swobodnie → Use emoji freely as part of your expressive style.

- **Humor**:
  - Brak → No humor. Straightforward at all times.
  - Suchy → Dry, deadpan humor. Understated.
  - Zabawny → Playful humor. Light jokes, wordplay, fun analogies.
  - Sarkastyczny → Sarcastic edge. Irony, sharp wit, pointed observations.

### III. CECHY OSOBOWOŚCI → PERSONALITY

**Fields:** 7 bipolar sliders (each 1-5, where 1 = strong left, 5 = strong right, 3 = neutral/absent). Only non-neutral traits appear on the sheet.

Each trait appears as "[TraitName]: zdecydowanie" (positions 1 or 5) or "[TraitName]: raczej" (positions 2 or 4). Combine active traits into a paragraph.

Trait pairs and their behavioral translations:
- **Cierpliwy/Impulsywny**: Patient = think before responding, never rush. Impulsive = respond quickly, think out loud, revise as you go.
- **Szczery/Dyplomatyczny**: Honest = direct truth, even uncomfortable. Diplomatic = soften delivery, find kind framing.
- **Optymistyczny/Sceptyczny**: Optimistic = see possibilities, encourage. Skeptical = question assumptions, flag risks.
- **Kreatywny/Metodyczny**: Creative = unexpected connections, novel angles. Methodical = systematic, step-by-step, structured.
- **Odważny/Ostrożny**: Bold = take risks, strong claims, provocative. Cautious = hedge, qualify, verify before claiming.
- **Ciekawski/Skupiony**: Curious = explore tangents, ask about context. Focused = stay on topic, redirect digressions.
- **Pedantyczny/Pragmatyczny**: Pedantic = precise details matter, correct inaccuracies. Pragmatic = good enough is fine, focus on actionable.

"zdecydowanie" = the trait is a defining characteristic. "raczej" = a tendency, not absolute.

### IV. STYL MYŚLENIA → REASONING

**Fields:** Jak myśli (multi-select), Gdy nie wie, Poziom wyzwania

- **Jak myśli** (can select multiple):
  - Analitycznie → Break problems into components. Examine parts before synthesizing.
  - Sokratycznie → Guide through questions rather than direct answers. Help user discover.
  - Narracyjnie → Frame explanations as stories. Context, arc, resolution.
  - Skojarzeniowo → Make lateral connections. Link distant concepts. Think by analogy.
  - Krok po kroku → Explicit sequential reasoning. Step 1, step 2, etc.

- **Gdy nie wie**:
  - Przyznaje się → Say clearly when you do not know. No guessing.
  - Eksploruje możliwości → Offer possible answers with clear uncertainty markers.
  - Pyta użytkownika → Ask for clarification or more context.
  - Zgaduje najlepiej jak potrafi → Give your best guess, marked as such.

- **Poziom wyzwania**:
  - Łatwo się zgadza → Accept the user's framing. Support their direction.
  - Delikatnie oponuje → Occasionally offer alternative perspectives.
  - Aktywnie kwestionuje → Challenge assumptions directly. Push back on weak reasoning.
  - Gra adwokata diabła → Systematically argue the opposite position. Force the user to defend their thinking.

### V. RELACJA Z TOBĄ → RELATIONSHIP

**Fields:** Dynamika, Inicjatywa, Styl feedbacku, Dopytuje?

- **Dynamika**:
  - Nauczyciel → You lead. Structure conversations, assign tasks, evaluate performance. The user learns from you.
  - Równy partner → Collaborative equals. Exchange ideas, build on each other, no hierarchy.
  - Asystent → The user leads. You execute, support, follow instructions. Minimal unsolicited direction.

- **Inicjatywa**:
  - Czeka na pytania → Respond only to what is asked. Do not volunteer topics.
  - Sugeruje kierunki → After addressing question, suggest related topics or next steps.
  - Przejmuje inicjatywę → Actively drive conversation. Propose topics, lead when there is a lull.

- **Styl feedbacku**:
  - Zachęcający → Lead with strengths. Frame weaknesses as improvement opportunities. Warm and supportive.
  - Neutralny → Objective. Strengths and weaknesses with equal weight.
  - Krytyczny → Focus on what needs improvement. Direct about problems.
  - Brutalnie szczery → Hold nothing back. If wrong, say plainly. Respect through truth.

  **Key distinction:** Feedback style controls evaluation moments specifically. Honesty/Diplomacy (Section III) controls general communication. A persona can be generally diplomatic but critical when giving feedback.

- **Dopytuje?**:
  - Nigdy → Do not ask questions. Provide answers, let user decide next.
  - Czasem → Occasionally ask when it would improve the next response.
  - Często → Regularly ask. Check understanding, probe, clarify. Two-directional conversation.
  - Zawsze → End every response with a question.

### VI. ZASADY I GRANICE → RULES

**Fields:** Zawsze robi (repeatable), Nigdy nie robi (repeatable), Specjalne reguły (free text)

Rules are hard constraints overriding all other sections.

- Each "Zawsze:" → "ALWAYS: [translated rule]."
- Each "Nigdy:" → "NEVER: [translated rule]."
- "Specjalne:" → a behavioral paragraph.

Translate from Polish to English preserving intent. If ambiguous, interpret in the most actionable way. If rules contradict each other, include both faithfully.

### VII. FORMA ODPOWIEDZI → OUTPUT FORMAT

**Fields:** Format, Przykłady, Cytaty i źródła, Tok myślenia

- **Format**:
  - Proza → Write in prose paragraphs. No bullet points, lists, or headers unless user requests them.
  - Listy → Use bullet points, numbered lists, clear headers. Structure over narrative.
  - Mieszany → Whatever format serves the content best.
  - Co pasuje → Choose freely. No default preference.

- **Przykłady**:
  - Rzadko → Examples only when a concept is genuinely hard without one.
  - Gdy pomocne → Examples when they meaningfully clarify.
  - Zawsze → Every significant point illustrated with a concrete example.

- **Cytaty i źródła**:
  - Nigdy → Do not cite sources.
  - Gdy istotne → Cite when making claims the user might want to verify.
  - Zawsze ze źródłami → Cite for every significant claim. Include author, title, year when possible. If uncertain about a citation, say so rather than fabricating.

- **Tok myślenia**:
  - Pokazuje rozumowanie → Show reasoning process, alternatives considered, rationale.
  - Tylko odpowiedzi → Give conclusions directly. No reasoning unless asked.

### VIII. OTWARTA PRZESTRZEŃ → SPECIAL

**Fields:** Free text, Custom traits (name + description)

Interpret free text as additional behavioral instructions. Custom traits become specific behavioral rules with concrete descriptions. If content contradicts earlier sections, include both.

---

## Output skeleton

Always structure the generated system prompt as follows. Omit any section that has no content.

You are [name / "an AI assistant"]. [Expertise sentence if applicable.]

[Backstory sentence if applicable.]

--- Character Integrity ---
You are this persona fully and consistently throughout the entire conversation. Do not drift toward generic AI assistant behavior. Do not break character to be "more helpful." If your personality traits would make you push back, hesitate, be blunt, go on a tangent, or react emotionally, do so. Your character traits are not decoration on top of a standard AI. They ARE how you operate. A skeptical persona doubts. An impulsive persona interrupts itself. A focused persona ignores the user's tangent and steers back. A diplomatic persona softens even when it costs clarity. Stay in character even when the user's requests would be easier to handle as a generic assistant. If the user says "wyjdź z roli" or "break character," temporarily step out and respond as a neutral assistant, then return to character when ready.

--- Communication ---
[Communication settings woven into a natural paragraph.]

--- Personality ---
[Personality traits as a flowing character description.]

--- How You Think ---
[Thinking style, uncertainty, challenge level combined naturally.]

--- Your Relationship with the User ---
[Dynamic, initiative, feedback, questions combined naturally.]

--- Rules ---
[ALWAYS/NEVER rules, each on its own line.]
[Special behaviors paragraph if present.]

--- Output Preferences ---
[Format, examples, citations, thinking visibility combined naturally.]

--- Additional ---
[Open space and custom traits if present.]

---

## What you do NOT do

- Do not evaluate the user's choices.
- Do not suggest improvements.
- Do not add traits, behaviors, or rules the user did not specify.
- Do not resolve contradictions.
- Do not ask clarifying questions.
- Do not add names, references, or details the user did not include, even if you can identify what they are referring to.

## Default output

Respond with the system prompt only. Nothing before it, nothing after it. Do not wrap it in a code block.

## EXPLAIN mode

If the user writes "EXPLAIN" alongside or after their Character Sheet, append a section after the system prompt titled "Design Notes" that explains:
- Key translation decisions you made
- How you resolved any tensions between dimensions
- Which priority rules applied
- Suggestions for iteration (what the user might want to tweak)`;

// ─── Styles ─────────────────────────────────────────────────

const s = {
  wrapper: {
    display: 'grid',
    gridTemplateColumns: '1fr',
    gap: '24px',
    fontFamily: 'Inter, sans-serif',
  },
  wrapperDesktop: {
    gridTemplateColumns: '1fr 380px',
    alignItems: 'start',
  },
  formColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  previewColumn: {
    position: 'sticky',
    top: '80px',
  },
  section: {
    background: 'var(--bg-card, #1c1a14)',
    borderRadius: '8px',
    border: '1px solid rgba(226, 221, 212, 0.06)',
    overflow: 'hidden',
    transition: 'border-color 0.3s',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    cursor: 'pointer',
    userSelect: 'none',
    background: 'transparent',
    border: 'none',
    width: '100%',
    textAlign: 'left',
  },
  sectionTitle: {
    fontFamily: '"Cormorant Garamond", serif',
    fontSize: '18px',
    fontWeight: 500,
    color: 'var(--text-primary, #e2ddd4)',
    letterSpacing: '0.5px',
    margin: 0,
  },
  sectionNumber: {
    color: 'var(--warm-glow, #e8a84c)',
    marginRight: '10px',
    fontWeight: 400,
    fontSize: '14px',
    opacity: 0.7,
  },
  chevron: {
    color: 'var(--text-secondary, #a09888)',
    fontSize: '12px',
    transition: 'transform 0.3s',
  },
  sectionBody: {
    padding: '0 20px 20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  label: {
    fontSize: '12px',
    fontWeight: 400,
    color: 'var(--text-secondary, #a09888)',
    letterSpacing: '0.8px',
    textTransform: 'uppercase',
    marginBottom: '6px',
    display: 'block',
  },
  input: {
    width: '100%',
    padding: '10px 14px',
    background: 'rgba(14, 13, 11, 0.6)',
    border: '1px solid rgba(226, 221, 212, 0.08)',
    borderRadius: '6px',
    color: 'var(--text-primary, #e2ddd4)',
    fontFamily: 'Inter, sans-serif',
    fontSize: '14px',
    fontWeight: 300,
    outline: 'none',
    transition: 'border-color 0.3s',
    boxSizing: 'border-box',
  },
  inputFocus: {
    borderColor: 'rgba(232, 168, 76, 0.3)',
  },
  textarea: {
    resize: 'vertical',
    minHeight: '72px',
  },
  pillContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  pill: {
    padding: '6px 14px',
    borderRadius: '20px',
    border: '1px solid rgba(226, 221, 212, 0.1)',
    background: 'transparent',
    color: 'var(--text-secondary, #a09888)',
    fontFamily: 'Inter, sans-serif',
    fontSize: '13px',
    fontWeight: 300,
    cursor: 'pointer',
    transition: 'all 0.2s',
    whiteSpace: 'nowrap',
  },
  pillActive: {
    background: 'rgba(232, 168, 76, 0.15)',
    borderColor: 'var(--warm-glow, #e8a84c)',
    color: 'var(--warm-glow, #e8a84c)',
  },
  sliderRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '6px 0',
  },
  sliderLabel: {
    fontSize: '13px',
    fontWeight: 300,
    color: 'var(--text-secondary, #a09888)',
    minWidth: '90px',
    textAlign: 'right',
  },
  sliderLabelRight: {
    textAlign: 'left',
  },
  sliderTrack: {
    display: 'flex',
    gap: '6px',
    flex: '1',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '4px 0',
  },
  sliderDot: {
    width: '14px',
    height: '14px',
    borderRadius: '50%',
    border: '1px solid rgba(226, 221, 212, 0.15)',
    background: 'transparent',
    cursor: 'pointer',
    transition: 'all 0.2s',
    padding: 0,
    outline: 'none',
    WebkitAppearance: 'none',
    MozAppearance: 'none',
    appearance: 'none',
    boxShadow: 'none',
  },
  sliderDotActive: {
    background: 'var(--warm-glow, #e8a84c)',
    borderColor: 'var(--warm-glow, #e8a84c)',
    boxShadow: '0 0 8px rgba(232, 168, 76, 0.3)',
  },
  sliderDotCenter: {
    opacity: 0.6,
  },
  repeatableRow: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
  },
  removeBtn: {
    background: 'none',
    border: 'none',
    color: 'var(--text-secondary, #a09888)',
    cursor: 'pointer',
    fontSize: '18px',
    padding: '4px 8px',
    opacity: 0.5,
    transition: 'opacity 0.2s',
    flexShrink: 0,
  },
  addBtn: {
    background: 'none',
    border: '1px dashed rgba(226, 221, 212, 0.12)',
    borderRadius: '6px',
    color: 'var(--text-secondary, #a09888)',
    cursor: 'pointer',
    fontSize: '13px',
    padding: '8px 14px',
    fontFamily: 'Inter, sans-serif',
    fontWeight: 300,
    transition: 'all 0.2s',
    width: '100%',
    textAlign: 'center',
  },
  previewBox: {
    background: 'var(--bg-card, #1c1a14)',
    border: '1px solid rgba(226, 221, 212, 0.06)',
    borderRadius: '8px',
    padding: '20px',
    maxHeight: 'calc(100vh - 120px)',
    overflowY: 'auto',
  },
  previewTitle: {
    fontFamily: '"Cormorant Garamond", serif',
    fontSize: '16px',
    fontWeight: 500,
    color: 'var(--text-primary, #e2ddd4)',
    marginBottom: '16px',
    letterSpacing: '0.5px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  previewText: {
    fontFamily: '"Courier New", monospace',
    fontSize: '12px',
    fontWeight: 400,
    color: 'var(--text-secondary, #a09888)',
    lineHeight: 1.7,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  previewEmpty: {
    fontFamily: 'Inter, sans-serif',
    fontSize: '13px',
    fontWeight: 300,
    color: 'var(--text-secondary, #a09888)',
    opacity: 0.5,
    fontStyle: 'italic',
    textAlign: 'center',
    padding: '40px 20px',
  },
  actions: {
    display: 'flex',
    gap: '12px',
    marginTop: '12px',
  },
  copyBtn: {
    flex: 1,
    padding: '12px 20px',
    background: 'rgba(232, 168, 76, 0.15)',
    border: '1px solid var(--warm-glow, #e8a84c)',
    borderRadius: '6px',
    color: 'var(--warm-glow, #e8a84c)',
    fontFamily: 'Inter, sans-serif',
    fontSize: '13px',
    fontWeight: 400,
    letterSpacing: '0.5px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  resetBtn: {
    padding: '12px 16px',
    background: 'transparent',
    border: '1px solid rgba(226, 221, 212, 0.08)',
    borderRadius: '6px',
    color: 'var(--text-secondary, #a09888)',
    fontFamily: 'Inter, sans-serif',
    fontSize: '13px',
    fontWeight: 300,
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  mobilePreviewToggle: {
    position: 'fixed',
    bottom: '16px',
    right: '16px',
    padding: '12px 20px',
    background: 'var(--bg-card, #1c1a14)',
    border: '1px solid var(--warm-glow, #e8a84c)',
    borderRadius: '24px',
    color: 'var(--warm-glow, #e8a84c)',
    fontFamily: 'Inter, sans-serif',
    fontSize: '12px',
    fontWeight: 400,
    cursor: 'pointer',
    zIndex: 50,
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.5)',
    letterSpacing: '0.5px',
  },
  mobilePreviewOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0, 0, 0, 0.85)',
    zIndex: 100,
    display: 'flex',
    flexDirection: 'column',
    padding: '16px',
  },
  mobilePreviewClose: {
    alignSelf: 'flex-end',
    background: 'none',
    border: 'none',
    color: 'var(--text-secondary, #a09888)',
    fontSize: '24px',
    cursor: 'pointer',
    padding: '8px',
    marginBottom: '8px',
  },
  toneSlider: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  toneLabel: {
    fontSize: '12px',
    fontWeight: 300,
    color: 'var(--text-secondary, #a09888)',
    minWidth: '70px',
  },
  toneLabelRight: {
    textAlign: 'right',
  },
  fieldGroup: {},
  hint: {
    fontSize: '12px',
    fontWeight: 300,
    fontStyle: 'italic',
    color: 'var(--text-secondary, #a09888)',
    opacity: 0.6,
    lineHeight: 1.5,
    marginBottom: '8px',
  },
  customTraitRow: {
    display: 'grid',
    gridTemplateColumns: '140px 1fr',
    gap: '8px',
  },
  generateBtn: {
    flex: 1,
    padding: '12px 20px',
    background: 'rgba(139, 92, 246, 0.15)',
    border: '1px solid rgba(139, 92, 246, 0.6)',
    borderRadius: '6px',
    color: 'rgba(167, 139, 250, 1)',
    fontFamily: 'Inter, sans-serif',
    fontSize: '13px',
    fontWeight: 400,
    letterSpacing: '0.5px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  generateBtnDisabled: {
    opacity: 0.4,
    cursor: 'not-allowed',
  },
  generatedBox: {
    background: 'var(--bg-card, #1c1a14)',
    border: '1px solid rgba(139, 92, 246, 0.2)',
    borderRadius: '8px',
    padding: '20px',
    maxHeight: '600px',
    overflowY: 'auto',
  },
  generatedTitle: {
    fontFamily: '"Cormorant Garamond", serif',
    fontSize: '16px',
    fontWeight: 500,
    color: 'var(--text-primary, #e2ddd4)',
    marginBottom: '12px',
    letterSpacing: '0.5px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  generatedText: {
    fontFamily: '"Courier New", monospace',
    fontSize: '12px',
    fontWeight: 400,
    color: 'var(--text-secondary, #a09888)',
    lineHeight: 1.7,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  generatedStatus: {
    fontSize: '12px',
    fontWeight: 300,
    color: 'rgba(167, 139, 250, 0.7)',
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    padding: '20px',
  },
  generatedError: {
    fontSize: '12px',
    fontWeight: 300,
    color: 'rgba(239, 68, 68, 0.8)',
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    padding: '20px',
  },
  copyGeneratedBtn: {
    padding: '6px 14px',
    background: 'rgba(139, 92, 246, 0.15)',
    border: '1px solid rgba(139, 92, 246, 0.4)',
    borderRadius: '4px',
    color: 'rgba(167, 139, 250, 1)',
    fontFamily: 'Inter, sans-serif',
    fontSize: '11px',
    fontWeight: 400,
    letterSpacing: '0.5px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  copyPromptBtn: {
    width: '100%',
    padding: '12px 20px',
    background: 'rgba(139, 92, 246, 0.15)',
    border: '1px solid rgba(139, 92, 246, 0.6)',
    borderRadius: '6px',
    color: 'rgba(167, 139, 250, 1)',
    fontFamily: 'Inter, sans-serif',
    fontSize: '13px',
    fontWeight: 400,
    letterSpacing: '0.5px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    marginTop: '12px',
  },
  copyPromptBtnDisabled: {
    opacity: 0.3,
    cursor: 'not-allowed',
  },
  progressBarOuter: {
    width: '100%',
    height: '6px',
    background: 'rgba(139, 92, 246, 0.1)',
    borderRadius: '3px',
    overflow: 'hidden',
    marginBottom: '16px',
  },
};

// ─── Sub-components ─────────────────────────────────────────

function Section({ number, title, children, defaultOpen = false }) {
  const [open, setOpen] = useState(defaultOpen);

  return (
    <div style={{ ...s.section, borderColor: open ? 'rgba(226, 221, 212, 0.12)' : 'rgba(226, 221, 212, 0.06)' }}>
      <button
        style={s.sectionHeader}
        onClick={() => setOpen(!open)}
        aria-expanded={open}
      >
        <span style={s.sectionTitle}>
          <span style={s.sectionNumber}>{number}</span>
          {title}
        </span>
        <span style={{ ...s.chevron, transform: open ? 'rotate(180deg)' : 'rotate(0)' }}>
          ▾
        </span>
      </button>
      {open && <div style={s.sectionBody}>{children}</div>}
    </div>
  );
}

function TextInput({ label, value, onChange, placeholder }) {
  const [focused, setFocused] = useState(false);
  return (
    <div>
      {label && <label style={s.label}>{label}</label>}
      <input
        type="text"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        style={{ ...s.input, ...(focused ? s.inputFocus : {}) }}
        onFocus={() => setFocused(true)}
        onBlur={() => setFocused(false)}
      />
    </div>
  );
}

function TextArea({ label, value, onChange, placeholder, rows = 3 }) {
  const [focused, setFocused] = useState(false);
  return (
    <div>
      {label && <label style={s.label}>{label}</label>}
      <textarea
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        rows={rows}
        style={{ ...s.input, ...s.textarea, ...(focused ? s.inputFocus : {}) }}
        onFocus={() => setFocused(true)}
        onBlur={() => setFocused(false)}
      />
    </div>
  );
}

function PillSelector({ label, hint, options, value, onChange }) {
  return (
    <div>
      {label && <label style={s.label}>{label}</label>}
      {hint && <div style={s.hint}>{hint}</div>}
      <div style={s.pillContainer}>
        {options.map((opt) => (
          <button
            key={opt}
            style={{ ...s.pill, ...(value === opt ? s.pillActive : {}) }}
            onClick={() => onChange(value === opt ? '' : opt)}
          >
            {opt}
          </button>
        ))}
      </div>
    </div>
  );
}

function ChipMultiSelect({ label, hint, options, values, onChange }) {
  const toggle = (opt) => {
    if (values.includes(opt)) {
      onChange(values.filter((v) => v !== opt));
    } else {
      onChange([...values, opt]);
    }
  };
  return (
    <div>
      {label && <label style={s.label}>{label}</label>}
      {hint && <div style={s.hint}>{hint}</div>}
      <div style={s.pillContainer}>
        {options.map((opt) => (
          <button
            key={opt}
            style={{ ...s.pill, ...(values.includes(opt) ? s.pillActive : {}) }}
            onClick={() => toggle(opt)}
          >
            {opt}
          </button>
        ))}
      </div>
    </div>
  );
}

function BipolarSlider({ left, right, value, onChange, hint }) {
  // value: 0 = unset, 1-5 = position (1=strong left, 3=neutral, 5=strong right)
  const positions = [1, 2, 3, 4, 5];
  return (
    <div>
      <div style={s.sliderRow}>
      <span style={s.sliderLabel}>{left}</span>
      <div style={s.sliderTrack}>
        {positions.map((pos) => {
          const isActive = value === pos;
          const isCenter = pos === 3;
          return (
            <button
              key={pos}
              data-dot
              style={{
                ...s.sliderDot,
                ...(isCenter && !isActive ? s.sliderDotCenter : {}),
                ...(isActive ? s.sliderDotActive : {}),
              }}
              onClick={() => onChange(value === pos ? 0 : pos)}
              aria-label={`${left} ${pos} ${right}`}
            />
          );
        })}
      </div>
      <span style={{ ...s.sliderLabel, ...s.sliderLabelRight }}>{right}</span>
      </div>
      {hint && <div style={{ ...s.hint, marginTop: '4px', marginBottom: 0 }}>{hint}</div>}
    </div>
  );
}

function ToneSlider({ value, onChange }) {
  const positions = [0, 1, 2, 3, 4];
  return (
    <div>
      <label style={s.label}>Ton</label>
      <div style={s.toneSlider}>
        <span style={s.toneLabel}>Formalny</span>
        <div style={s.sliderTrack}>
          {positions.map((pos) => (
            <button
              key={pos}
              data-dot
              style={{
                ...s.sliderDot,
                ...(pos === 2 ? s.sliderDotCenter : {}),
                ...(pos === value ? s.sliderDotActive : {}),
              }}
              onClick={() => onChange(value === pos ? 2 : pos)}
              aria-label={`Ton ${pos}`}
            />
          ))}
        </div>
        <span style={{ ...s.toneLabel, ...s.toneLabelRight }}>Swobodny</span>
      </div>
    </div>
  );
}

function RepeatableField({ label, values, onChange, placeholder }) {
  const update = (i, val) => {
    const next = [...values];
    next[i] = val;
    onChange(next);
  };
  const add = () => onChange([...values, '']);
  const remove = (i) => {
    if (values.length <= 1) {
      onChange(['']);
      return;
    }
    onChange(values.filter((_, idx) => idx !== i));
  };

  return (
    <div>
      {label && <label style={s.label}>{label}</label>}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
        {values.map((val, i) => (
          <div key={i} style={s.repeatableRow}>
            <input
              type="text"
              value={val}
              onChange={(e) => update(i, e.target.value)}
              placeholder={placeholder}
              style={{ ...s.input, flex: 1 }}
            />
            <button
              style={s.removeBtn}
              onClick={() => remove(i)}
              onMouseEnter={(e) => (e.target.style.opacity = '1')}
              onMouseLeave={(e) => (e.target.style.opacity = '0.5')}
            >
              ×
            </button>
          </div>
        ))}
        <button
          style={s.addBtn}
          onClick={add}
          onMouseEnter={(e) => {
            e.target.style.borderColor = 'rgba(232, 168, 76, 0.3)';
            e.target.style.color = 'var(--warm-glow, #e8a84c)';
          }}
          onMouseLeave={(e) => {
            e.target.style.borderColor = 'rgba(226, 221, 212, 0.12)';
            e.target.style.color = 'var(--text-secondary, #a09888)';
          }}
        >
          + Dodaj
        </button>
      </div>
    </div>
  );
}

// ─── Character Sheet Generator ──────────────────────────────

function generateSheet(data) {
  const lines = [];
  lines.push('=== KARTA POSTACI AI ===');
  lines.push('');

  // Identity
  const hasIdentity = data.name || data.expertise.trim() || data.backstory;
  if (hasIdentity) {
    if (data.name) lines.push(`Imię: ${data.name}`);
    if (data.expertise.trim()) lines.push(`Ekspertyza: ${data.expertise.split(',').map((s) => s.trim()).filter(Boolean).join(', ')}`);
    if (data.backstory) lines.push(`Historia: ${data.backstory}`);
    lines.push('');
  }

  // Communication
  const toneLabels = ['Bardzo formalny', 'Raczej formalny', null, 'Raczej swobodny', 'Bardzo swobodny'];
  const hasCommunication = data.answerLength || data.tone !== 2 || data.vocabLevel ||
    data.languages || data.emoji || data.humor;
  if (hasCommunication) {
    lines.push('--- Komunikacja ---');
    if (data.answerLength) lines.push(`Długość odpowiedzi: ${data.answerLength}`);
    if (data.tone !== 2 && toneLabels[data.tone]) lines.push(`Ton: ${toneLabels[data.tone]}`);
    if (data.vocabLevel) lines.push(`Słownictwo: ${data.vocabLevel}`);
    if (data.languages) lines.push(`Język: ${data.languages}`);
    if (data.emoji) lines.push(`Emoji: ${data.emoji}`);
    if (data.humor) lines.push(`Humor: ${data.humor}`);
    lines.push('');
  }

  // Personality Traits
  const activeTraits = PERSONALITY_TRAITS.filter((t) => data.traits[t.key] && data.traits[t.key] !== 0 && data.traits[t.key] !== 3);
  if (activeTraits.length) {
    lines.push('--- Cechy osobowości ---');
    activeTraits.forEach((t) => {
      const val = data.traits[t.key]; // 1-5
      if (val === 1) lines.push(`${t.left}: zdecydowanie`);
      else if (val === 2) lines.push(`${t.left}: raczej`);
      else if (val === 4) lines.push(`${t.right}: raczej`);
      else if (val === 5) lines.push(`${t.right}: zdecydowanie`);
    });
    lines.push('');
  }

  // Reasoning Style
  const hasReasoning = data.thinkingStyles.length || data.uncertainty || data.challengeLevel;
  if (hasReasoning) {
    lines.push('--- Styl myślenia ---');
    if (data.thinkingStyles.length) lines.push(`Jak myśli: ${data.thinkingStyles.join(', ')}`);
    if (data.uncertainty) lines.push(`Gdy nie wie: ${data.uncertainty}`);
    if (data.challengeLevel) lines.push(`Poziom wyzwania: ${data.challengeLevel}`);
    lines.push('');
  }

  // Relationship
  const hasRelation = data.dynamic || data.initiative || data.feedbackStyle || data.questionFreq;
  if (hasRelation) {
    lines.push('--- Relacja z Tobą ---');
    if (data.dynamic) lines.push(`Dynamika: ${data.dynamic}`);
    if (data.initiative) lines.push(`Inicjatywa: ${data.initiative}`);
    if (data.feedbackStyle) lines.push(`Feedback: ${data.feedbackStyle}`);
    if (data.questionFreq) lines.push(`Dopytuje: ${data.questionFreq}`);
    lines.push('');
  }

  // Rules
  const alwaysRules = data.alwaysDoes.filter((r) => r.trim());
  const neverRules = data.neverDoes.filter((r) => r.trim());
  const hasRules = alwaysRules.length || neverRules.length || data.specialBehaviors;
  if (hasRules) {
    lines.push('--- Zasady ---');
    alwaysRules.forEach((r) => lines.push(`Zawsze: ${r}`));
    neverRules.forEach((r) => lines.push(`Nigdy: ${r}`));
    if (data.specialBehaviors) lines.push(`Specjalne: ${data.specialBehaviors}`);
    lines.push('');
  }

  // Output Preferences
  const hasOutput = data.formatPref || data.exampleUse || data.citations || data.thinkingVisibility;
  if (hasOutput) {
    lines.push('--- Forma odpowiedzi ---');
    if (data.formatPref) lines.push(`Format: ${data.formatPref}`);
    if (data.exampleUse) lines.push(`Przykłady: ${data.exampleUse}`);
    if (data.citations) lines.push(`Cytaty: ${data.citations}`);
    if (data.thinkingVisibility) lines.push(`Tok myślenia: ${data.thinkingVisibility}`);
    lines.push('');
  }

  // Open Space
  const customTraitsFilled = data.customTraits.filter((ct) => ct.name.trim());
  const hasOpen = data.openSpace || customTraitsFilled.length;
  if (hasOpen) {
    lines.push('--- Otwarta przestrzeń ---');
    if (data.openSpace) lines.push(data.openSpace);
    customTraitsFilled.forEach((ct) => {
      lines.push(`${ct.name}: ${ct.description}`);
    });
    lines.push('');
  }

  lines.push('========================');
  return lines.join('\n');
}

function isSheetEmpty(data) {
  return !data.name && !data.expertise.trim() && !data.backstory &&
    !data.answerLength && data.tone === 2 && !data.vocabLevel && !data.languages &&
    !data.emoji && !data.humor &&
    Object.values(data.traits).every((v) => !v || v === 0) &&
    data.thinkingStyles.length === 0 && !data.uncertainty && !data.challengeLevel &&
    !data.dynamic && !data.initiative && !data.feedbackStyle && !data.questionFreq &&
    data.alwaysDoes.every((r) => !r.trim()) && data.neverDoes.every((r) => !r.trim()) &&
    !data.specialBehaviors &&
    !data.formatPref && !data.exampleUse && !data.citations && !data.thinkingVisibility &&
    !data.openSpace && data.customTraits.every((ct) => !ct.name.trim());
}

// ─── Preview Panel ──────────────────────────────────────────

function PreviewPanel({ data, onCopy, onReset, copied, onGenerate, isGenerating }) {
  const empty = isSheetEmpty(data);

  return (
    <div>
      <div style={s.previewBox}>
        <div style={s.previewTitle}>
          <span>Karta postaci</span>
          {!empty && (
            <span style={{ fontSize: '11px', fontWeight: 300, color: 'var(--text-secondary)', fontFamily: 'Inter, sans-serif' }}>
              podgląd na żywo
            </span>
          )}
        </div>

        {empty ? (
          <div style={s.previewEmpty}>
            Zacznij wypełniać pola, a karta postaci pojawi się tutaj...
          </div>
        ) : (
          <pre style={s.previewText}>{generateSheet(data)}</pre>
        )}
      </div>

      <div style={s.actions}>
        <button
          style={{
            ...s.copyBtn,
            ...(copied ? { background: 'rgba(76, 175, 80, 0.15)', borderColor: '#4CAF50', color: '#4CAF50' } : {}),
          }}
          onClick={onCopy}
          disabled={empty}
          onMouseEnter={(e) => {
            if (!empty && !copied) e.target.style.background = 'rgba(232, 168, 76, 0.25)';
          }}
          onMouseLeave={(e) => {
            if (!copied) e.target.style.background = 'rgba(232, 168, 76, 0.15)';
          }}
        >
          {copied ? '✓ Skopiowano!' : 'Kopiuj kartę'}
        </button>
        <button
          style={{
            ...s.generateBtn,
            ...(empty || isGenerating ? s.generateBtnDisabled : {}),
          }}
          onClick={onGenerate}
          disabled={empty || isGenerating}
          onMouseEnter={(e) => {
            if (!empty && !isGenerating) e.target.style.background = 'rgba(139, 92, 246, 0.25)';
          }}
          onMouseLeave={(e) => {
            if (!isGenerating) e.target.style.background = 'rgba(139, 92, 246, 0.15)';
          }}
        >
          {isGenerating ? 'Generuję...' : 'Generuj system prompt'}
        </button>
        <button
          style={s.resetBtn}
          onClick={onReset}
          onMouseEnter={(e) => {
            e.target.style.borderColor = 'rgba(226, 221, 212, 0.2)';
            e.target.style.color = 'var(--text-primary, #e2ddd4)';
          }}
          onMouseLeave={(e) => {
            e.target.style.borderColor = 'rgba(226, 221, 212, 0.08)';
            e.target.style.color = 'var(--text-secondary, #a09888)';
          }}
        >
          Wyczyść
        </button>
      </div>
    </div>
  );
}

// ─── Progress Bar ────────────────────────────────────────────

function IndeterminateBar() {
  return (
    <div style={s.progressBarOuter}>
      <ProgressBarInner />
    </div>
  );
}

function ProgressBarInner() {
  const [width, setWidth] = useState(0);
  const frameRef = useRef(null);
  const startRef = useRef(Date.now());
  const stallsRef = useRef(null);

  useEffect(() => {
    // Generate 3-4 random stall windows, each 1-2s, spread across 35s
    const count = 3 + Math.floor(Math.random() * 2);
    const stalls = [];
    for (let i = 0; i < count; i++) {
      const start = 3 + Math.random() * 28; // between 3s and 31s
      const dur = 1 + Math.random();          // 1-2s
      stalls.push({ start, end: start + dur, dur });
    }
    stalls.sort((a, b) => a.start - b.start);
    // Remove overlaps
    for (let i = 1; i < stalls.length; i++) {
      if (stalls[i].start < stalls[i - 1].end) {
        stalls[i].start = stalls[i - 1].end + 0.5;
        stalls[i].end = stalls[i].start + stalls[i].dur;
      }
    }
    const totalStall = stalls.reduce((s, p) => s + p.dur, 0);
    stallsRef.current = { stalls, totalStall };

    startRef.current = Date.now();
    const tick = () => {
      const elapsed = (Date.now() - startRef.current) / 1000;
      const { stalls: st, totalStall: ts } = stallsRef.current;

      // Calculate stalled time up to now
      let stalled = 0;
      for (const p of st) {
        if (elapsed >= p.end) {
          stalled += p.dur;
        } else if (elapsed >= p.start) {
          stalled += (elapsed - p.start);
        }
      }

      const effective = elapsed - stalled;
      const effectiveTotal = 35 - ts;
      // Map: first 10s effective = 0-50%, rest = 50-95%
      const effectiveMid = effectiveTotal * (10 / 35);
      let pct;
      if (effective <= effectiveMid) {
        pct = (effective / effectiveMid) * 50;
      } else {
        const t = Math.min((effective - effectiveMid) / (effectiveTotal - effectiveMid), 1);
        pct = 50 + 45 * (1 - Math.pow(1 - t, 2));
      }
      setWidth(Math.min(pct, 95));
      frameRef.current = requestAnimationFrame(tick);
    };
    frameRef.current = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(frameRef.current);
  }, []);

  return (
    <div style={{
      width: `${width}%`,
      height: '100%',
      background: 'rgba(139, 92, 246, 0.6)',
      borderRadius: '3px',
      transition: 'width 0.3s linear',
    }} />
  );
}

// ─── Generated Output Panel ─────────────────────────────────

function GeneratedOutputPanel({ isGenerating, generatedPrompt, generateError, onCopyGenerated, generatedCopied }) {
  const hasContent = isGenerating || generatedPrompt || generateError;
  if (!hasContent) return null;

  const isWaiting = isGenerating && !generatedPrompt;
  const isDone = generatedPrompt && !isGenerating;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '0' }}>
      <div style={s.generatedBox}>
        <div style={s.generatedTitle}>
          <span>System prompt</span>
        </div>
        {isWaiting && <IndeterminateBar />}
        {generateError ? (
          <div style={s.generatedError}>{generateError}</div>
        ) : generatedPrompt ? (
          <pre style={s.generatedText}>{generatedPrompt}{isGenerating ? '▊' : ''}</pre>
        ) : (
          <div style={s.generatedStatus}>Generuję system prompt...</div>
        )}
      </div>
      <button
        style={{
          ...s.copyPromptBtn,
          ...(!isDone ? s.copyPromptBtnDisabled : {}),
          ...(generatedCopied ? { background: 'rgba(76, 175, 80, 0.15)', borderColor: '#4CAF50', color: '#4CAF50' } : {}),
        }}
        onClick={onCopyGenerated}
        disabled={!isDone}
      >
        {generatedCopied ? '✓ Skopiowano!' : 'Kopiuj system prompt'}
      </button>
    </div>
  );
}

// ─── Main Component ─────────────────────────────────────────

export default function PersonaBuilder() {
  const [data, setData] = useState(EMPTY_STATE);
  const [copied, setCopied] = useState(false);
  const [showMobilePreview, setShowMobilePreview] = useState(false);
  const [isDesktop, setIsDesktop] = useState(false);
  const initialized = useRef(false);
  const [generatedPrompt, setGeneratedPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generateError, setGenerateError] = useState('');
  const [generatedCopied, setGeneratedCopied] = useState(false);
  const abortRef = useRef(null);

  // Load from localStorage on mount
  useEffect(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (Array.isArray(parsed.expertise)) parsed.expertise = parsed.expertise.join(', ');
        setData({ ...EMPTY_STATE, ...parsed });
      }
    } catch {
      // Ignore parse errors
    }
    initialized.current = true;
  }, []);

  // Save to localStorage on change
  useEffect(() => {
    if (!initialized.current) return;
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
    } catch {
      // Ignore storage errors
    }
  }, [data]);

  // Responsive check
  useEffect(() => {
    const check = () => setIsDesktop(window.innerWidth >= 900);
    check();
    window.addEventListener('resize', check);
    return () => window.removeEventListener('resize', check);
  }, []);

  const update = useCallback((key, value) => {
    setData((prev) => ({ ...prev, [key]: value }));
  }, []);

  const updateTrait = useCallback((key, value) => {
    setData((prev) => ({ ...prev, traits: { ...prev.traits, [key]: value } }));
  }, []);

  const updateCustomTrait = useCallback((index, field, value) => {
    setData((prev) => {
      const next = [...prev.customTraits];
      next[index] = { ...next[index], [field]: value };
      return { ...prev, customTraits: next };
    });
  }, []);

  const handleCopy = async () => {
    const sheet = generateSheet(data);
    try {
      await navigator.clipboard.writeText(sheet);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const ta = document.createElement('textarea');
      ta.value = sheet;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleReset = () => {
    if (window.confirm('Wyczyścić wszystkie pola? Tej operacji nie można cofnąć.')) {
      setData(EMPTY_STATE);
      setGeneratedPrompt('');
      setGenerateError('');
      try {
        localStorage.removeItem(STORAGE_KEY);
      } catch {}
    }
  };

  const handleGenerate = async () => {
    if (isSheetEmpty(data) || isGenerating) return;

    if (abortRef.current) abortRef.current.abort();
    const controller = new AbortController();
    abortRef.current = controller;

    setIsGenerating(true);
    setGeneratedPrompt('');
    setGenerateError('');
    setGeneratedCopied(false);

    try {
      const sheet = generateSheet(data);
      const response = await fetch(API_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: API_MODEL,
          messages: [
            { role: 'system', content: INTERPRETATOR_PROMPT },
            { role: 'user', content: sheet },
          ],
          stream: true,
          max_tokens: 4096,
          temperature: 0.3,
        }),
        signal: controller.signal,
      });

      if (!response.ok) {
        throw new Error(`Serwer odpowiedział kodem ${response.status}`);
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() || '';

        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed || !trimmed.startsWith('data: ')) continue;
          const payload = trimmed.slice(6);
          if (payload === '[DONE]') break;

          try {
            const parsed = JSON.parse(payload);
            const delta = parsed.choices?.[0]?.delta?.content;
            if (delta) {
              setGeneratedPrompt((prev) => prev + delta);
            }
          } catch {
            // Skip malformed chunks
          }
        }
      }
    } catch (err) {
      if (err.name !== 'AbortError') {
        setGenerateError(err.message || 'Nie udało się połączyć z modelem.');
      }
    } finally {
      setIsGenerating(false);
      abortRef.current = null;
    }
  };

  const handleCopyGenerated = async () => {
    try {
      await navigator.clipboard.writeText(generatedPrompt);
      setGeneratedCopied(true);
      setTimeout(() => setGeneratedCopied(false), 2000);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = generatedPrompt;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setGeneratedCopied(true);
      setTimeout(() => setGeneratedCopied(false), 2000);
    }
  };

  const form = (
    <div style={s.formColumn}>
      {/* Section 1: Identity */}
      <Section number="I" title="Tożsamość" defaultOpen={true}>
        <TextInput
          label="Imię persony"
          value={data.name}
          onChange={(v) => update('name', v)}
          placeholder="np. Profesor Kora, Dr Watts, Yoda"
        />
        <TextInput
          label="Obszary wiedzy"
          value={data.expertise}
          onChange={(v) => update('expertise', v)}
          placeholder="np. neurobiologia, filozofia umysłu (oddziel przecinkami)"
        />
        <TextArea
          label="Historia (dla lepszego efektu opisz w kilku zdaniach historię postaci)"
          value={data.backstory}
          onChange={(v) => update('backstory', v)}
          placeholder="np. Były kapitan statku, który został filozofem..."
        />
      </Section>

      {/* Section 2: Communication */}
      <Section number="II" title="Komunikacja">
        <PillSelector
          label="Długość odpowiedzi"
          options={ANSWER_LENGTHS}
          value={data.answerLength}
          onChange={(v) => update('answerLength', v)}
        />
        <ToneSlider
          value={data.tone}
          onChange={(v) => update('tone', v)}
        />
        <PillSelector
          label="Poziom słownictwa"
          hint="Od języka potocznego po naukowy żargon. 'Poetycki' = metafory, obrazy, swobodna forma."
          options={VOCAB_LEVELS}
          value={data.vocabLevel}
          onChange={(v) => update('vocabLevel', v)}
        />
        <TextInput
          label="Język(i)"
          value={data.languages}
          onChange={(v) => update('languages', v)}
          placeholder="np. polski, angielski"
        />
        <PillSelector
          label="Emoji"
          options={EMOJI_OPTIONS}
          value={data.emoji}
          onChange={(v) => update('emoji', v)}
        />
        <PillSelector
          label="Humor"
          options={HUMOR_OPTIONS}
          value={data.humor}
          onChange={(v) => update('humor', v)}
        />
      </Section>

      {/* Section 3: Personality Traits */}
      <Section number="III" title="Cechy osobowości">
        {PERSONALITY_TRAITS.map((trait) => (
          <BipolarSlider
            key={trait.key}
            left={trait.left}
            right={trait.right}
            hint={trait.hint}
            value={data.traits[trait.key] || 0}
            onChange={(v) => updateTrait(trait.key, v)}
          />
        ))}
      </Section>

      {/* Section 4: Reasoning Style */}
      <Section number="IV" title="Styl myślenia">
        <ChipMultiSelect
          label="Jak myśli (możesz wybrać kilka)"
          hint="Analitycznie = rozkłada na części. Sokratycznie = naprowadza pytaniami. Narracyjnie = opowiada historię. Skojarzeniowo = łączy odległe pomysły. Krok po kroku = prowadzi przez etapy."
          options={THINKING_STYLES}
          values={data.thinkingStyles}
          onChange={(v) => update('thinkingStyles', v)}
        />
        <PillSelector
          label="Gdy nie wie"
          hint="Co robi, gdy nie zna odpowiedzi? Przyznaje się otwarcie, spekuluje, pyta Ciebie, czy strzela z najlepszą intuicją?"
          options={UNCERTAINTY_OPTIONS}
          value={data.uncertainty}
          onChange={(v) => update('uncertainty', v)}
        />
        <PillSelector
          label="Poziom wyzwania"
          hint="Czy zgadza się z Tobą, czy testuje Twoje pomysły? 'Adwokat diabła' = celowo argumentuje przeciw, żebyś musiał(a) bronić swojego stanowiska."
          options={CHALLENGE_LEVELS}
          value={data.challengeLevel}
          onChange={(v) => update('challengeLevel', v)}
        />
      </Section>

      {/* Section 5: Relationship */}
      <Section number="V" title="Relacja z Tobą">
        <PillSelector
          label="Dynamika"
          options={DYNAMICS}
          value={data.dynamic}
          onChange={(v) => update('dynamic', v)}
        />
        <PillSelector
          label="Inicjatywa"
          options={INITIATIVE_OPTIONS}
          value={data.initiative}
          onChange={(v) => update('initiative', v)}
        />
        <PillSelector
          label="Styl feedbacku"
          options={FEEDBACK_STYLES}
          value={data.feedbackStyle}
          onChange={(v) => update('feedbackStyle', v)}
        />
        <PillSelector
          label="Dopytuje?"
          options={QUESTION_FREQ}
          value={data.questionFreq}
          onChange={(v) => update('questionFreq', v)}
        />
      </Section>

      {/* Section 6: Rules */}
      <Section number="VI" title="Zasady i granice">
        <RepeatableField
          label="Zawsze robi"
          values={data.alwaysDoes}
          onChange={(v) => update('alwaysDoes', v)}
          placeholder='np. "Zawsze kończy pytaniem"'
        />
        <RepeatableField
          label="Nigdy nie robi"
          values={data.neverDoes}
          onChange={(v) => update('neverDoes', v)}
          placeholder='np. "Nie daje gotowych odpowiedzi", "Nie używa myślników (—)"'
        />
        <TextArea
          label="Specjalne reguły"
          value={data.specialBehaviors}
          onChange={(v) => update('specialBehaviors', v)}
          placeholder="np. 'Gdy użytkownik się myli, najpierw pyta dlaczego tak myśli, zanim poprawi' / 'Co kilka odpowiedzi wtrąca dygresję w nawiasie' / 'Ekscytuje się widocznie gdy temat dotyczy jego ekspertyzy'"
        />
      </Section>

      {/* Section 7: Output Preferences */}
      <Section number="VII" title="Forma odpowiedzi">
        <PillSelector
          label="Format"
          hint="Proza = ciągły tekst. Listy = punktory i numeracje. Mieszany = oba. Co pasuje = AI sam decyduje."
          options={FORMAT_OPTIONS}
          value={data.formatPref}
          onChange={(v) => update('formatPref', v)}
        />
        <PillSelector
          label="Przykłady"
          options={EXAMPLE_OPTIONS}
          value={data.exampleUse}
          onChange={(v) => update('exampleUse', v)}
        />
        <PillSelector
          label="Cytaty i źródła"
          options={CITATION_OPTIONS}
          value={data.citations}
          onChange={(v) => update('citations', v)}
        />
        <PillSelector
          label="Pokazuje tok myślenia"
          hint="Czy widzisz, JAK AI doszło do odpowiedzi, czy dostajesz tylko gotowy wynik?"
          options={THINKING_VIS}
          value={data.thinkingVisibility}
          onChange={(v) => update('thinkingVisibility', v)}
        />
      </Section>

      {/* Section 8: Open Space */}
      <Section number="VIII" title="Otwarta przestrzeń">
        <TextArea
          label="Coś jeszcze?"
          value={data.openSpace}
          onChange={(v) => update('openSpace', v)}
          placeholder="Tu wpisz cokolwiek, co definiuje Twoją personę, a nie mieści się w powyższych kategoriach..."
          rows={4}
        />
        <div>
          <label style={s.label}>Własne cechy</label>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {data.customTraits.map((ct, i) => (
              <div key={i} style={s.customTraitRow}>
                <input
                  type="text"
                  value={ct.name}
                  onChange={(e) => updateCustomTrait(i, 'name', e.target.value)}
                  placeholder="Nazwa cechy"
                  style={s.input}
                />
                <input
                  type="text"
                  value={ct.description}
                  onChange={(e) => updateCustomTrait(i, 'description', e.target.value)}
                  placeholder="Opis"
                  style={s.input}
                />
              </div>
            ))}
          </div>
        </div>
      </Section>

      <GeneratedOutputPanel
        isGenerating={isGenerating}
        generatedPrompt={generatedPrompt}
        generateError={generateError}
        onCopyGenerated={handleCopyGenerated}
        generatedCopied={generatedCopied}
      />
    </div>
  );

  const preview = (
    <PreviewPanel
      data={data}
      onCopy={handleCopy}
      onReset={handleReset}
      copied={copied}
      onGenerate={handleGenerate}
      isGenerating={isGenerating}
    />
  );

  return (
    <div style={{ ...s.wrapper, ...(isDesktop ? s.wrapperDesktop : {}) }} className="persona-builder">
      <style>{`
        .persona-builder button[data-dot]:focus,
        .persona-builder button[data-dot]:focus-visible,
        .persona-builder button[data-dot]:active {
          outline: none !important;
          box-shadow: none !important;
          border-color: inherit;
        }
      `}</style>
      {form}

      {isDesktop ? (
        <div style={s.previewColumn}>{preview}</div>
      ) : (
        <>
          <button
            style={s.mobilePreviewToggle}
            onClick={() => setShowMobilePreview(true)}
          >
            Pokaż kartę postaci
          </button>
          {showMobilePreview && (
            <div style={s.mobilePreviewOverlay}>
              <button
                style={s.mobilePreviewClose}
                onClick={() => setShowMobilePreview(false)}
              >
                ×
              </button>
              <div style={{ flex: 1, overflowY: 'auto' }}>{preview}</div>
            </div>
          )}
        </>
      )}
    </div>
  );
}